import type { Flatten } from "./tensorType.ts";
export declare class Tensor {
    constructor(data: Flatten);
    private flatten;
    private _data;
    private _strides;
    private _shape;
    get data(): Float64Array;
    get ndim(): number;
    get size(): number;
    get strides(): Int32Array;
    get shape(): Int32Array;
    static add(tensor_one: Tensor, tensor_two: Tensor): Tensor;
    static sub(tensor_one: Tensor, tensor_two: Tensor): Tensor;
    static max(tensor: Tensor, axis: number[], keepdims: boolean): Tensor;
    static min(tensor: Tensor, axis: number[], keepdims: boolean): Tensor;
    static reset_pool(): null;
    static destory_pool(): null;
    static div(parameter_one: Tensor | number, parameter_two: Tensor | number): Tensor | never;
    static mul(parameter_one: Tensor, parameter_two: Tensor | number): Tensor;
    static Matrix_mul(tensor_one: Tensor, tensor_two: Tensor): Tensor;
    static add_broadcasted(tensor_one: Tensor, tensor_two: Tensor): Tensor;
    static sub_broadcasted(tensor_one: Tensor, tensor_two: Tensor): Tensor;
    static reshape(tensor: Tensor, new_shape: number[], new_dim: number): Tensor;
    static pow(parameter_one: Tensor | number, parameter_two: Tensor | number): Tensor;
    static ln(tensor: Tensor): Tensor;
    static euqal(tensor_one: Tensor, tensor_two: Tensor): Tensor;
    static euqal_broadcasted(tensor_one: Tensor, tensor_two: Tensor): Tensor;
    static ones_like(tensor: Tensor): Tensor;
    static zeros_like(tensor: Tensor): Tensor;
    static sin(tensor: Tensor): Tensor;
    static cos(tensor: Tensor): Tensor;
    static transpose(tensor: Tensor, axis: number[]): Tensor;
    static make_contiguous(tensor: Tensor): null;
    add(tensor: Tensor): Tensor;
    sub(tensor: Tensor): Tensor;
    max(axis: number[], keepdims: boolean): Tensor;
    min(axis: number[], keepdims: boolean): Tensor;
    div(parameter: Tensor | number, S_div_T?: boolean): Tensor | never;
    mul(parameter: Tensor | number): Tensor;
    add_broadcasted(tensor: Tensor): Tensor;
    sub_broadcasted(tensor: Tensor): Tensor;
    reshape(new_shape: number[], new_dim: number): Tensor;
    pow(parameter: number, S_pow_T?: boolean): Tensor;
    ln(): Tensor;
    equal(tensor: Tensor): Tensor;
    equal_broadcasted(tensor: Tensor): Tensor;
    ones_like(): Tensor;
    zeros_like(): Tensor;
    sin(): Tensor;
    cos(): Tensor;
    transpose(axis: number[]): Tensor;
    make_contiguous(): null;
}
